core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
     re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

main/urls.py
from audioop import add
from unicodedata import name
from django.urls import path
from main.views import *


json_patterns = [
    path('json/blockchain', get_blockchain)
]

urlpatterns = [

    path('', IndexView.as_view(), name="index"),
    path('signup', RegisterView.as_view(), name="signup"),
    path('account', account, name="account"),
    path('transaction/<str:recv_address>', transaction, name="transaction"),
    path('mining', mining , name="mining"),
    path('blockchain', blockchain, name="blockchain"),
    path('block/<str:block_hash>', blockview, name="block"),
    path('node', TemplateView.as_view(template_name = "main/menu/node.html"), name="node"),
    path('blockchain/add-block', add_block, name="add-block"),
    path('share', TemplateView.as_view(template_name= "main/menu/share.html"), name="share")

]+json_patterns

main/models.py
import hashlib
import json, rsa
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from core.utils import sign

class LillyUser(AbstractUser):
    public_key = models.TextField(unique=True)
    private_key = models.TextField(unique=True)
    amount = models.IntegerField(default=0)
    address = models.CharField(max_length=32, unique=True)

    def get_private_key(self):
        return rsa.PrivateKey.load_pkcs1(self.private_key)

    def get_public_key(self):
        return rsa.PublicKey.load_pkcs1(self.public_key)

    def send_amount(self, amount):
        self.amount -= amount
        self.save()

    def recieve_amount(self,amount):
        self.amount += amount
        self.save()

    def save(self, *args, **kwargs) -> None:
        if len(self.address) != 32:
            PublicKey, PrivateKey = rsa.newkeys(1024)
            self.private_key = rsa.PublicKey.save_pkcs1(PrivateKey).decode("ascii")
            self.public_key = rsa.PublicKey.save_pkcs1(PublicKey).decode("ascii")
            self.address = hashlib.md5(self.private_key.encode()).hexdigest()
        return super().save(*args, **kwargs)

    
class Transaction(models.Model):
    sender = models.ForeignKey(LillyUser, on_delete=models.CASCADE, related_name="sender")
    reciever =  models.ForeignKey(LillyUser, on_delete=models.CASCADE, related_name="reciever")
    amount = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)
    signature = models.TextField()
    confirmed = models.BooleanField(default=False)
    hash = models.CharField(max_length=64, unique=True)
    
    def signTransaction(self):
        private_key =self.sender.get_private_key()
        self.signature =  sign(self.calculateHash(), private_key)
        return self.signature

    def calculateHash(self):
        hashEncoded = json.dumps(self.get_data(), sort_keys=True).encode()
        return hashlib.sha256(hashEncoded).hexdigest()
    
    def makeTransaction(self):
        self.sender.send_amount(self.amount)
        self.reciever.recieve_amount(self.amount)

    def save(self,*args, **kwargs) -> None:
        self.signature = self.signTransaction()
        self.hash = self.get_hash()
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.sender} - {self.reciever} - {self.amount}"

    def get_hash(self):
        return hashlib.sha256(json.dumps(self.get_transaction_data()).encode()).hexdigest()


    def get_data(self):
        return {
            "index":self.pk,
            "sender":self.sender.address,
            "reciever":self.reciever.address,
            "amount":self.amount,
            "timestamp":str(self.timestamp),
        }

    def get_confirmed(self):
        self.confirm = True
        self.save()

    def get_transaction_data(self):
        data = self.get_data()
        data.update({
            "index":self.pk,
            "signature":self.signature,
            "hash":self.hash
            })
        return data


class Block(models.Model):
    # serial number of block chain
    index = models.IntegerField()
    # User who mined
    miner = models.ForeignKey(LillyUser, on_delete=models.CASCADE)
    # Hash of previous block
    prev_hash = models.CharField(max_length = 64, verbose_name='Previous Hash')
    # Hash of the block
    hash = models.CharField(max_length = 64, verbose_name='Block Hash')
    # timestamp when block mined
    timestamp = models.DateTimeField(auto_now_add=True)
    # list of transactions
    transactions = models.ManyToManyField(Transaction)
    # number of transactions
    no_of_transactions = models.IntegerField()
    # number of times hash were generated
    nonce = models.CharField(max_length=1000)
    # number of zeroes in front of hash
    difficulty = models.IntegerField(default=settings.MINING_DIFFICULTY)
    # Block Reward
    block_reward = models.FloatField(default=settings.MINING_REWARD)
    # Block Size
    block_size = models.IntegerField()

        

main/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import LillyUser

class LillyUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = LillyUser
        fields = ('username', 'email', 'password1', 'password2')

class LillyUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = LillyUser
        fields = ('username', 'amount')

main/views.py
from django.http import  JsonResponse
from django.urls import reverse
from main.mine import MineBlock
from django.conf import settings
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from main.forms import LillyUserCreationForm
from django.contrib.auth import login
from django.db.models import Sum
from django.views.generic import TemplateView, FormView
from django.contrib import messages
from main.mine_genesis import BlockCreator, ValidateBlock, block_json
from main.models import Block, Transaction, LillyUser
from django.contrib.auth.decorators import login_required

class IndexView(TemplateView):
    template_name = "main/index.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse("account"))
        return super().get(request, *args, **kwargs)


@login_required
def transaction(request, recv_address):
    context = dict()
    if request.method == "POST":
        reciever_address = request.POST.get("address")
        amount = int(request.POST.get("amount"))
        sender_obj = request.user
        if LillyUser.objects.filter(address = reciever_address).exists():
            reciever_obj = LillyUser.objects.get(address = reciever_address)
            if reciever_obj == sender_obj:
                messages.error(request, "sender is same as reciever")
            elif sender_obj.amount < amount:
                messages.error(request, "Low Balance!")
            else:
                Transaction.objects.create(
                    sender = sender_obj,
                    reciever = reciever_obj,
                    amount = amount
                )
                messages.success(request, "Transactions successfull")
        else:
            messages.error(request, "User does not exist")
    context["transactions"] = Transaction.objects.filter(sender = request.user)

    context["recv_address"] = recv_address if recv_address != "default" else None
    return render(request, "main/menu/transaction.html", context)

@login_required
def account(request):
    context = {
        "user_transaction_url": request.build_absolute_uri("transaction/"+request.user.address),
        "pending_coins":Transaction.objects.filter(confirmed = False, reciever = request.user).aggregate(Sum("amount")).get("amount__sum")
    }
    print(context.get("user_transaction_url"))
    return render(request, "main/menu/account.html", context)

@login_required
def add_block(request):
    if request.method == "POST":
        block_hash = request.POST.get("block_hash")
        nonce = int(request.POST.get("nonce"))
        transaction_hashes = request.POST.getlist("transaction_hash")
        if ValidateBlock(request, transaction_hashes, block_hash, nonce).validate():
            BlockCreator(request, block_hash, nonce, transaction_hashes).create_block()
            return redirect(reverse("blockchain"))
        else:
            return redirect(reverse("mining"))

@login_required
def mining(request):
    if Transaction.objects.count() == 0:
        main_user = LillyUser.objects.get(username = "main")
        Transaction.objects.create(sender = main_user, reciever= request.user, amount=0)
    context = dict()
    if request.method == "POST":
        transaction_hashes = request.POST.getlist("transactions")
        if transaction_hashes:    
            json_data = block_json(request, transaction_hashes)
            context["transaction_hashes"] = transaction_hashes
            context["json_data"] = json_data
            block_hash, nonce = MineBlock(json_data).get_block_hash()
            context["block_hash"] = block_hash
            context["nonce"] = nonce
            context["block_json_data"] = {
                "nonce":nonce,
                "block_hash":block_hash
            }
    context["block_reward"] = settings.MINING_REWARD
    context["transactions"] = Transaction.objects.filter(confirmed = False)
    return render(request, "main/menu/mining.html", context)

def blockchain(request):
    if Block.objects.count() == 0:
        return redirect(reverse("mining"))
    context = {
        "block_list":Block.objects.all()
    }
    return render(request, "main/menu/blockchain.html", context)

def blockview(request, block_hash):
    context = {
        "Block": Block.objects.get(hash = block_hash)
    }
    return render(request, "main/menu/block.html", context)


class RegisterView(FormView):
    template_name = "registration/signup.html"
    form_class = LillyUserCreationForm
    success_url = reverse_lazy("account")

    def form_valid(self, form:LillyUserCreationForm):
        user = form.save(commit=False)
        user.amount = settings.STARTING_AMOUNT
        user.save()
        login(self.request, user)
        return super().form_valid(form)
    
# JSON RESPONSE FUNCTIONS

def get_blockchain(request):
    json_data = dict()
    blockchain_obj = Block.objects.all()
    json_data["blockchain"] = []
    for block in blockchain_obj:
        block_dict = {
            "index":block.index,
            "hash":block.hash,
            "timestamp":block.timestamp,
            "miner":block.miner.username,
            "prev_hash":block.prev_hash,
            "no_of_transactions": block.no_of_transactions,
            "difficulty":block.difficulty,
            "size":block.block_size,
            "nonce":block.nonce,
            "reward":block.block_reward,
            "transactions":[]
        }
        for transaction in block.transactions.all():
            block_dict["transactions"].append({
                "hash":transaction.hash,
                "amount":transaction.amount,
                "timestamp":transaction.timestamp
            })
        json_data["blockchain"].append(block_dict)

    return JsonResponse(json_data)

main/templates/main/menu/account.html
{% extends 'main/menu.html' %}
{% load qr_code %}
{% load static %}
{% block menu %}

<div class="row">
    <div class="col-md-4">
        <div class="card shadow m-3 text-center" style="border-radius: 30px;">
            {% qr_from_text  user_transaction_url %}
            <p class="bg-success text-light text-uppercase"><b>Scan To Pay</b></p>
            <p class="text-muted">Only accepts LC</p>
            <div class="card-body bg-light">
                <h5 class="card-title">@{{user.username}}</h5>
                <p class="card-text">{{user.email}}</p>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card shadow m-3" style="border-radius: 40px;">
            <div class="card-body">
                <h2 class="card-text mb-2">
                    Balance: <span>{{user.amount}}</span>
                    {% if pending_coins %}
                    <p style="font-size: small;" class="text-muted">Pending Coins: <span>{{pending_coins}}</span> (mine transactions to get LCs)</p>
                    {% endif %}
                </h2>
                <div class="card-text mb-3">LC address: <input class="form-control" type="text"
                        value="{{ user.address }}" readonly></div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">RSA PUBLIC KEY </label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" readonly
                        aria-describedby="RSAHelp">
                            {{ user.public_key }}
                        </textarea>
                    <div id="RSAHelp" class="form-text">LC transactions uses RSA algorithm for secure signature</div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    svg {
        display: block;
        margin: auto;
    }
</style>


{% endblock menu %}

main/templates/main/menu/block.html
{% extends 'main/menu.html' %}
{% block menu %}
<div class="container">
    <div class="card m-3 p-3 shadow table-responsive">
        <h3 class="card-title mb-3">Block {{ Block.index }}</h3>
        <table class="table">
            <tbody>
                <tr>
                    <td>Hash</td>
                    <td>{{ Block.hash }}</td>
                </tr>
                <tr>
                    <td>Timestamp</td>
                    <td>{{ Block.timestamp }}</td>
                </tr>
                <tr>
                    <td>Height</td>
                    <td>{{ Block.index }}</td>
                </tr>
                <tr>
                    <td>Miner</td>
                    <td>{{ Block.miner }}</td>
                </tr>
                <tr>
                    <td>Previous Hash</td>
                    <td>{{ Block.prev_hash | default:"No previous Hash for Block 1" }}</td>
                </tr>
                <tr>
                    <td>No of Transactions</td>
                    <td>{{ Block.no_of_transactions }}</td>
                </tr>
                <tr>
                    <td>Difficulty</td>
                    <td>{{ Block.difficulty }}</td>
                </tr>
                <tr>
                    <td>Size</td>
                    <td>{{ Block.block_size }} bytes</td>
                </tr>
                <tr>
                    <td>Nonce</td>
                    <td>{{ Block.nonce }}</td>
                </tr>
                <tr>
                    <td>Block Reward</td>
                    <td>{{ Block.block_reward }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="card m-3 p-3 shadow table-responsive">
        <h3 class="card-title mb-3">Block Transactions</h3>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Hash</th>
                        <th>amount</th>
                        <th>timestamp</th>
                    </tr>
                </thead>
                <tbody>
                    {% for transaction in Block.transactions.all %}
                    <tr>
                        <td>{{ transaction.hash }}</td>
                        <td>{{ transaction.amount }}</td>
                        <td>{{ transaction.timestamp }}</td>
                    </tr>
                    {% endfor %}
            
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock menu %}

main/templates/main/menu/blockchain.html
{% extends 'main/menu.html' %}
{% block menu %}
<div class="container">
    <h1># Block Chain</h1>
    <div class="table-responsive card shadow">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Index</th>
                    <th>Hash</th>
                    <th>Miner</th>
                    <th>Mined</th>
                </tr>
            </thead>
            <tbody>
                {% for block in block_list %}
                <tr>
                    <td scope="row">{{ block.index }}</td>
                    <td><a class="link-dark" href="{% url 'block' block.hash %}">{{ block.hash | upper}}</a></td>
                    <td>{{ block.miner.username }}</td>
                    <td>{{ block.timestamp }}</td>
                </tr>
                {% empty %}
                <div class="alert alert-warning" role="alert">
                    <strong>No block was mined</strong>
                </div>

                {% endfor %}

            </tbody>
        </table>
    </div>

</div>
{% endblock menu %}

main/templates/main/menu/mining.html
{% extends 'main/menu.html' %}
{% load static %}
{% block menu %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1><i class="bi bi-gear-wide-connected"></i> Mining Area</h1>
        </div>
        <div class="card-body">
            <h3 class="card-title">Unconfirmed Transactions</h3>
            <small>Showing oldest 20 unconfirmed transactions (maximum transaction in block limited to 20)</small>
            <small>Select Transactions below to get data</small>
            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th></th>
                        <th>Hash</th>
                        <th>Amount</th>
                        <th>Time</th>
                    </tr>
                    <form method="post" action="{% url 'mining' %}">
                        {% csrf_token %}
                        {% for transaction in transactions %}
                        <tr>
                            <td>
                                <div class="form-check"><input class="form-check-input" name="transactions"
                                        type="checkbox" value="{{ transaction.hash }}"></div>
                            </td>
                            <td>{{ transaction.hash }}</td>
                            <td>{{ transaction.amount }}</td>
                            <td>{{ transaction.timestamp }}</td>
                        </tr>
                        {% empty %}
                        <div class="alert alert-warning" role="alert">
                            <strong>No Unconfirmed Transactions </strong>
                        </div>
                        {% endfor %}
                        <button class="btn btn-dark m-3"><b><i class="bi bi-cpu me-2"></i> MINE BLOCK</b></button>
                    </form>
                </table>
            </div>
        </div>
    </div>

    <div class="card-group my-2">
        {% if json_data %}
        <div class="card m-1">
            <div class="card-body">
                <div class="mb-3">
                    <label for="json_data" class="form-label">MINING JSON DATA</label>
                    <textarea id="json_data" class="form-control" rows="8" readonly>{{ json_data }}</textarea>
                </div>
                <div id="spinner" class="spinner-border spinner-border-sm" role="status"></div>
                <p id="hash-text"></p>
                <div class="progress" role="progressbar">
                    <div id="hash-progress" class="progress-bar progress-bar-striped progress-bar-animated bg-black"
                        style="width: 0%"></div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="card m-1">
            <div class="card-body">
                <p class="card-text">Get Mining reward of {{ block_reward }} LC for a Block</p>
                <div class="mb-3">
                    <form method="post" action="{% url 'add-block' %}">
                        {% csrf_token %}
                        {% if transaction_hashes %}
                        <div class="mb-3">
                            <label class="form-label">List of Transactions</label>
                            <ul>
                                {% for hash in transaction_hashes %}
                                <li><input class="form-control mb-1" type="text" name="transaction_hash"
                                        value="{{ hash }}" readonly></li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}
                        <div class="mb-3">
                            <label for="id_block_hash" class="form-label">256-bit Mined Block Hash</label>
                            <input type="text" class="form-control" name="block_hash" maxlength="64" id="id_block_hash"
                                aria-describedby="helpHash">
                            <small id="helpHash" class="form-text text-muted">hash must be 64 char long and must follow
                                rules.</small>
                        </div>
                        <div class="mb-3">
                            <label for="id_nonce" class="form-label">Nonce Value</label>
                            <input type="text" class="form-control" id="nonce" name="nonce" maxlength="64"
                                aria-describedby="helpNonce">
                            <small id="helpNonce" class="form-text text-muted">nonce is value of trial error
                                loop</small>
                        </div>
                        <button type="submit" class="btn btn-dark">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{{ block_json_data | json_script:"json-data" }}
<script src="{% static 'js/mining.js' %}"></script>
{% endblock menu %}

main/templates/main/menu/transaction.html
{% extends 'main/menu.html' %}
{% load static %}
{% block menu %}
<div class="container my-3">
    <h1>Make a secure Transaction</h1>

    <div class="row">
        <div class="col-md-6">
            <div class="card p-3 m-3 shadow">
                {% for message in messages %}
                {% if message.tags == "error" %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    {{message}}
                </div>
                {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    {{message}}
                </div>
                {% endif %}
                {% endfor %}
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_reciever" class="form-label">LC address</label>
                        {% if recv_address %}
                        <input type="text" class="form-control" name="address" id="id_address"
                            value="{{ recv_address }}" aria-describedby="addressHelp" readonly>
                        {% else %}
                        <input type="text" class="form-control" name="address" id="id_address"
                            aria-describedby="addressHelp" required>
                        {% endif %}
                        <div class="form-text" id="addressHelp">128-bit LC address of reciever for anonymous
                            transaction</div>
                    </div>
                    <div class="mb-3">
                        <label for="id_amount" class="form-label">Amount</label>
                        <input type="number" class="form-control" name="amount" id="id_amount" max="" required>
                    </div>
                    <button type="submit" class="btn btn-dark">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock menu %}